### ISSUE TITLE
BE: Implement auth middleware

### ISSUE THREAD

**Issue by ThinkTink** [hatchways/team-cocoa-puffs#46]
We need a middleware function that can:
1) read the jwt token from the browser cookies
2) decode that token and find the corresponding user
3) pass on to the route function which user is authenticated

Here are some resources that may help, but be sure to adapt them to our use case (such as our our token is based just on the user's email):
https://medium.com/quick-code/handling-authentication-and-authorization-with-node-7f9548fedde8
https://developer.okta.com/blog/2019/10/03/painless-node-authentication

**Comment by bonnieli** [comment]
@peacebonez There is an existing middleware here that is commented out but not used anywhere in `dev` at the moment

https://github.com/hatchways/team-cocoa-puffs/blob/dev/middleware/auth.js
